/* unofficial gameplaySP kai
 *
 * Copyright (C) 2006 Exophase <exophase@gmail.com>
 * Copyright (C) 2007 takka <takka@tfact.net>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#ifndef MESSAGE_H
#define MESSAGE_H

#define MSG  message[option_language]

#define LANGUAGE_NUM 5

enum MESSAGE_ITEM
{
  MSG_TURBO,
  MSG_CHARGE,
  MSG_BUFFER,

  MSG_BROWSER_HELP,
  MSG_BROWSER_HELP_ROOT,

  MSG_MENU_DATE_FMT_0,
  MSG_MENU_DATE_FMT_1,

  MSG_MAIN_MENU_TITLE,

  MSG_MAIN_MENU_0,
  MSG_MAIN_MENU_1,
  MSG_MAIN_MENU_2,
  MSG_MAIN_MENU_3,
  MSG_MAIN_MENU_4,
  MSG_MAIN_MENU_5,
  MSG_MAIN_MENU_6,
  MSG_MAIN_MENU_CHEAT,
  MSG_MAIN_MENU_7,
  MSG_MAIN_MENU_8,
  MSG_MAIN_MENU_9,
  MSG_MAIN_MENU_10,
  MSG_MAIN_MENU_11,

  MSG_MAIN_MENU_HELP_0,
  MSG_MAIN_MENU_HELP_1,
  MSG_MAIN_MENU_HELP_2,
  MSG_MAIN_MENU_HELP_3,
  MSG_MAIN_MENU_HELP_4,
  MSG_MAIN_MENU_HELP_5,
  MSG_MAIN_MENU_HELP_6,
  MSG_MAIN_MENU_HELP_CHEAT,
  MSG_MAIN_MENU_HELP_7,
  MSG_MAIN_MENU_HELP_8,
  MSG_MAIN_MENU_HELP_9,
  MSG_MAIN_MENU_HELP_10,
  MSG_MAIN_MENU_HELP_11,

  MSG_OPTION_MENU_TITLE,

  MSG_OPTION_MENU_0,
  MSG_OPTION_MENU_1,
  MSG_OPTION_MENU_2,
  MSG_OPTION_MENU_SHOW_FPS,
  MSG_OPTION_MENU_3,
  MSG_OPTION_MENU_4,
  MSG_OPTION_MENU_5,
  MSG_OPTION_MENU_6,
  MSG_OPTION_MENU_7,
  MSG_OPTION_MENU_8,
  MSG_OPTION_MENU_9,
  MSG_OPTION_MENU_10,
  MSG_OPTION_MENU_DEFAULT,
  MSG_OPTION_MENU_11,

  MSG_OPTION_MENU_HELP_0,
  MSG_OPTION_MENU_HELP_1,
  MSG_OPTION_MENU_HELP_2,
  MSG_OPTION_MENU_HELP_SHOW_FPS,
  MSG_OPTION_MENU_HELP_3,
  MSG_OPTION_MENU_HELP_4,
  MSG_OPTION_MENU_HELP_5,
  MSG_OPTION_MENU_HELP_6,
  MSG_OPTION_MENU_HELP_7,
  MSG_OPTION_MENU_HELP_8,
  MSG_OPTION_MENU_HELP_9,
  MSG_OPTION_MENU_HELP_10,
  MSG_OPTION_MENU_HELP_DEFAULT,
  MSG_OPTION_MENU_HELP_11,

  MSG_OPTION_MENU_BLOCK_CHECKSUM_REUSE,
  MSG_OPTION_MENU_HELP_BLOCK_CHECKSUM_REUSE,

  MSG_OPTION_MENU_HBLANK_IRQ_WIN_START,
  MSG_OPTION_MENU_HELP_HBLANK_IRQ_WIN_START,
  MSG_OPTION_MENU_HBLANK_IRQ_WIN_END,
  MSG_OPTION_MENU_HELP_HBLANK_IRQ_WIN_END,

  MSG_STATE_MENU_DATE_FMT_0,
  MSG_STATE_MENU_DATE_FMT_1,
  MSG_STATE_MENU_DATE_NONE_0,
  MSG_STATE_MENU_DATE_NONE_1,

  MSG_STATE_MENU_STATE_NONE,

  MSG_STATE_MENU_TITLE,

  MSG_STATE_MENU_0,
  MSG_STATE_MENU_1,
  MSG_STATE_MENU_2,
  MSG_STATE_MENU_DELETE,

  MSG_STATE_MENU_HELP_0,
  MSG_STATE_MENU_HELP_1,
  MSG_STATE_MENU_HELP_2,

  MSG_PAD_MENU_TITLE,

  MSG_PAD_MENU_0,
  MSG_PAD_MENU_1,
  MSG_PAD_MENU_2,
  MSG_PAD_MENU_3,
  MSG_PAD_MENU_4,
  MSG_PAD_MENU_5,
  MSG_PAD_MENU_6,
  MSG_PAD_MENU_7,
  MSG_PAD_MENU_8,
  MSG_PAD_MENU_9,
  MSG_PAD_MENU_10,
  MSG_PAD_MENU_11,
  MSG_PAD_MENU_12,

  MSG_PAD_MENU_HELP_0,
  MSG_PAD_MENU_HELP_1,

  MSG_PAD_MENU_CFG_0,
  MSG_PAD_MENU_CFG_1,
  MSG_PAD_MENU_CFG_2,
  MSG_PAD_MENU_CFG_3,
  MSG_PAD_MENU_CFG_4,
  MSG_PAD_MENU_CFG_5,
  MSG_PAD_MENU_CFG_6,
  MSG_PAD_MENU_CFG_7,
  MSG_PAD_MENU_CFG_8,
  MSG_PAD_MENU_CFG_9,
  MSG_PAD_MENU_CFG_10,
  MSG_PAD_MENU_CFG_11,
  MSG_PAD_MENU_CFG_12,
  MSG_PAD_MENU_CFG_13,
  MSG_PAD_MENU_CFG_14,
  MSG_PAD_MENU_CFG_15,
  MSG_PAD_MENU_CFG_16,
  MSG_PAD_MENU_CFG_17,
  MSG_PAD_MENU_CFG_18,
  MSG_PAD_MENU_CFG_19,

  MSG_A_PAD_MENU_TITLE,

  MSG_A_PAD_MENU_0,
  MSG_A_PAD_MENU_1,
  MSG_A_PAD_MENU_2,
  MSG_A_PAD_MENU_3,
  MSG_A_PAD_MENU_4,
  MSG_A_PAD_MENU_5,
  MSG_A_PAD_MENU_6,

  MSG_A_PAD_MENU_HELP_0,
  MSG_A_PAD_MENU_HELP_1,
  MSG_A_PAD_MENU_HELP_2,

  MSG_CHEAT_MENU_TITLE,

  MSG_CHEAT_MENU_NON_LOAD,
  MSG_CHEAT_MENU_0,
  MSG_CHEAT_MENU_1,
  MSG_CHEAT_MENU_2,
  MSG_CHEAT_MENU_3,

  MSG_CHEAT_MENU_HELP_0,
  MSG_CHEAT_MENU_HELP_1,
  MSG_CHEAT_MENU_HELP_2,
  MSG_CHEAT_MENU_HELP_3,

  MSG_NON_LOAD_GAME,

  MSG_DAYW_0,
  MSG_DAYW_1,
  MSG_DAYW_2,
  MSG_DAYW_3,
  MSG_DAYW_4,
  MSG_DAYW_5,
  MSG_DAYW_6,

  MSG_YES,
  MSG_NO,

  MSG_ON,
  MSG_OFF,

  MSG_ENABLED,
  MSG_DISABLED,

  MSG_AUTO,
  MSG_MANUAL,

  MSG_RAM_DYNAREC_FULL_FLUSH,
  MSG_RAM_DYNAREC_PARTIAL_NO_REUSE,
  MSG_RAM_DYNAREC_PARTIAL_WITH_REUSE,

  MSG_EXITONLY,

  MSG_LOAD,
  MSG_SAVE,

  MSG_SCN_SCALED_NONE,
  MSG_SCN_SCALED_X15_GU,
  MSG_SCN_SCALED_X15_SW,
  MSG_SCN_SCALED_USER,
  MSG_SCN_SCALED_16X9_GU,

  MSG_LANG_JAPANESE,
  MSG_LANG_ENGLISH,
  MSG_LANG_CHS,
  MSG_LANG_CHT,

  MSG_SS_DATE_FMT_0,
  MSG_SS_DATE_FMT_1,

  MSG_ERR_SET_DIR_0,
  MSG_ERR_SET_DIR_1,
  MSG_ERR_SET_DIR_2,

  MSG_ERR_SS_PNG_0,
  MSG_ERR_SS_PNG_1,

  MSG_LOADING_ROM,
  MSG_SEARCHING_BACKUP_ID,

  MSG_GBA_SLEEP_MODE,

  MSG_ERR_LOAD_DIR_INI,

  MSG_ERR_BIOS_NONE,

  MSG_ERR_LOAD_GAMEPACK,
  MSG_ERR_OPEN_GAMEPACK,

  MSG_ERR_START_CALLBACK_THREAD,

  MSG_ERR_RESERVE_AUDIO_CHANNEL,
  MSG_ERR_START_SOUND_THREAD,

  MSG_ERR_MALLOC,

  MSG_ERR_CONT,
  MSG_ERR_QUIT,

  MSG_LOAD_STATE_NO,
  MSG_SAVE_STATE_NO,
  MSG_LOAD_STATE_AUTO,
  MSG_SAVE_STATE_AUTO,
  MSG_YES_NO,

  MSG_BLANK,
  
  CH_ICON_TEST,
  MH_ICON_TEST,

  MSG_MAIN_MENU_GAMECONFIG,
  MSG_MAIN_MENU_EMULATOR,
  
  MSG_MAIN_MENU_HELP_GAMECONFIG,
  MSG_MAIN_MENU_HELP_EMULATOR,
  MSG_MAIN_MENU_HELP_RETURNTOGAME,
  
  MSG_OPTION_MENU_SCREENSHOT,
  MSG_OPTION_MENU_VIDEORENDER,
  MSG_OPTION_MENU_OAMHIJACKSUPPORT,
  MSG_OPTION_MENU_VSYNCPSP,
  MSG_OPTION_MENU_THEMES,
  MSG_OPTION_MENU_CUSTOM_COLORS,
  MSG_OPTION_MENU_SWAP_BUTTONS,
  MSG_OPTION_MENU_DEFAULT_THEME,
  MSG_OPTION_MENU_DEFAULT_SETTINGS,

  MSG_OPTION_MENU_HELP_THEMES,
  MSG_OPTION_MENU_HELP_CUSTOM_COLORS,
  MSG_OPTION_MENU_HELP_SWAP_BUTTONS,
  MSG_OPTION_MENU_HELP_DEFAULT_KEYBIND,
  MSG_OPTION_MENU_HELP_DEFAULTKEYBIND,
  MSG_OPTION_MENU_HELP_DEFAULT_THEME,

  MSG_TOOLTIP_MAGNIFICATION,
  MSG_TOOLTIP_VIDEO_RENDERER,
  MSG_TOOLTIP_OAM_HIJACKING,
  MSG_TOOLTIP_FRAMESKIP_TYPE,
  MSG_TOOLTIP_FRAMESKIP_VALUE,
  MSG_TOOLTIP_RAM_DYNAREC_MODE,
  MSG_TOOLTIP_HBLANK_WIN_START,
  MSG_TOOLTIP_HBLANK_WIN_END,
  MSG_TOOLTIP_STACK_OPTIMIZE,
  MSG_TOOLTIP_AUTO_BACKUP,

  MSG_EMULATOR_MENU_TITLE,

  MSG_PREVIEW_TITLE,
  MSG_PREVIEW_ITEM_0,
  MSG_PREVIEW_ITEM_1,
  MSG_PREVIEW_ITEM_2,
  MSG_PREVIEW_ITEM_3,
  MSG_PREVIEW_ITEM_4,
  MSG_PREVIEW_ITEM_HELP,
  MSG_PREVIEW_ITEM_TOOLTIP,

  MSG_THEMES_OG,
  MSG_THEMES_DARK,
  MSG_THEMES_LIGHT,
  MSG_THEMES_BLUE,
  MSG_THEMES_GREEN,
  MSG_THEMES_RED,
  MSG_THEMES_PURPLE,
  MSG_THEMES_HIGH_CONTRAST,
  MSG_THEMES_RETRO,

  MSG_CUSTOM_COLOR_BG,
  MSG_CUSTOM_COLOR_ROM_INFO,
  MSG_CUSTOM_COLOR_ACTIVE_ITEM,
  MSG_CUSTOM_COLOR_INACTIVE_ITEM,
  MSG_CUSTOM_COLOR_TOOLTIP_TEXT,
  MSG_CUSTOM_COLOR_HELP_TEXT,
  MSG_CUSTOM_COLOR_INACTIVE_DIR,
  MSG_CUSTOM_COLOR_SCROLL_BAR,
  MSG_CUSTOM_COLOR_BATT_NORMAL,
  MSG_CUSTOM_COLOR_BATT_LOW,
  MSG_CUSTOM_COLOR_BATT_CHARG,
  
  MSG_CUSTOM_COLOR_HELP_ITEM,

  MSG_PICKER_OLD,
  MSG_PICKER_NEW,
  MSG_PICKER_CONTROLS,

  MSG_SWAP_BUTTONS_O_CONFIRMS,
  MSG_SWAP_BUTTONS_X_CONFIRMS,

  MSG_LANG_ITA,

  MSG_RENDERER_OLD,
  MSG_RENDERER_NEW,
  MSG_FMT_PNG,
  MSG_FMT_BMP,
  MSG_CLOCK_222,
  MSG_CLOCK_266,
  MSG_CLOCK_300,
  MSG_CLOCK_333,
  MSG_VOL_0,
  MSG_VOL_10,
  MSG_VOL_20,
  MSG_VOL_30,
  MSG_VOL_40,
  MSG_VOL_50,
  MSG_VOL_60,
  MSG_VOL_70,
  MSG_VOL_80,
  MSG_VOL_90,
  MSG_VOL_100,

  MSG_AUTO_SAVESTATE_LOAD_PROMPT,
  MSG_LOAD_ROM_AND_STATE,
  MSG_LOAD_STATE_FILE,
  MSG_ERR_ROM_NOT_FOUND,
  MSG_BROWSER_RECENT_GAMES,
  MSG_BROWSER_ALL_GAMES,

  MSG_MAIN_MENU_LINK,
  MSG_MAIN_MENU_HELP_LINK,
  MSG_LINK_MENU_TITLE,
  MSG_LINK_HOST,
  MSG_LINK_JOIN,
  MSG_LINK_DISCONNECT,
  MSG_LINK_HELP_HOST,
  MSG_LINK_HELP_JOIN,
  MSG_LINK_HELP_DISCONNECT,

  MSG_END
};

extern const char *message[LANGUAGE_NUM][MSG_END];

#endif /* MESSAGE_H */
